<class>
<keyword>class</keyword>
<identifier>Square</identifier>
<symbol>{</symbol>
<classVarDec>
<keyword>field</keyword>
<identifier>x</identifier>
<symbol>,</symbol>
<identifier>y</identifier>
<symbol>;</symbol>
</classVarDec>
<classVarDec>
<keyword>field</keyword>
<identifier>size</identifier>
<symbol>;</symbol>
</classVarDec>
<classVarDec>
<keyword></keyword>
